mongo:
  host: "127.0.0.1"
  port: 27017
  username: "username"
  password: "supaSecretPassword"
  database: "dbName"
  auth-database: "authDb"
errors:
  generic: "&cAn error occurred! &7(Contact the Dev Team)"
  no-permission: '&cInsufficient Permission!'